Add API for updating User
sedenardi/zoomapi pull request #8
Opened 2021-04-26 19:06 UTC by steelbrain

As advertised

2021-05-17 01:06 UTC, sedenardi commented on src/users.ts
>  }
Please maintain the newline at the end of files.

2021-05-17 01:06 UTC, sedenardi requested changes
Sorry for the delay. This looks good for the most part, just one very minor change.

2021-09-10 06:36 UTC, sedenardi commented
Hi there, I'm going to close this unless the requested change is made.

2021-09-15 02:29 UTC, steelbrain commented
Thanks for the reminder here @sedenardi.
The review comment mentions an EOF line, but I have checked on both, Github Web and in the files themselves, and there is an EOF line.

Can you please re-review? Thanks!

2021-09-17 04:45 UTC, sedenardi approved these changes

2021-09-17 04:45 UTC, merged

2021-09-17 04:48 UTC, sedenardi commented
Merged and published to `npm` as version `1.7.0`. Thanks again for your contribution!